name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract secrets into ENV variables
        run: |
          echo "REACT_APP_WEATHER_API_KEY=${{ secrets.REACT_APP_WEATHER_API_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_GEOCODE_API_KEY=${{ secrets.REACT_APP_GEOCODE_API_KEY }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t evansmanyala/hypercast:latest .
          docker push evansmanyala/hypercast:latest

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/hypercast"

      - name: Deploy to EC2
        run: |
          ssh -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/hypercast
            echo "REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}" > .env
            echo "REACT_APP_GEOCODE_API_KEY=${REACT_APP_GEOCODE_API_KEY}" >> .env
            docker-compose down
            docker-compose up -d --build
          EOF
